# Generated by Django 2.1.5 on 2019-01-31 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='money',
            field=models.IntegerField(default=1000000),
        ),
    ]
