# Generated by Django 2.1.5 on 2019-01-31 02:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_manufacturer_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='release',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 1, 31, 2, 58, 0, 442163, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
