# Generated by Django 2.1.5 on 2019-01-29 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HocSinh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=30)),
                ('ho', models.CharField(max_length=30)),
                ('ten_dem', models.CharField(max_length=30)),
                ('ngay_sinh', models.DateField()),
                ('chuc_vu', models.CharField(choices=[('LT', 'Lớp trưởng'), ('LP', 'Lớp phó'), ('BT', 'Bí thư'), ('TV', 'Thành viên')], default='TV', max_length=2)),
            ],
            options={
                'db_table': 'hoc_sinh',
            },
        ),
        migrations.CreateModel(
            name='Lop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=3)),
                ('khoi', models.IntegerField()),
                ('hoc_sinh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lops', related_query_name='lop', to='app.HocSinh')),
            ],
            options={
                'db_table': 'lop',
            },
        ),
    ]
