# Generated by Django 2.1.5 on 2019-01-29 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='app.Person')),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school', to='app.Person')),
            ],
        ),
    ]
