# Generated by Django 2.1.5 on 2019-01-29 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(max_length=50),
        ),
    ]
